# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('pymba', '0002_pymbawallpage_pymbawallpagelayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PymbaFinishingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(blank=True, max_length=250, null=True)),
                ('pattern', models.BooleanField(default=False)),
                ('color', models.CharField(default='white', max_length=250)),
                ('tiling_height', models.CharField(default='0', max_length=250)),
                ('tiling_pattern', models.BooleanField(default=False)),
                ('tiling_color', models.CharField(default='white', max_length=250)),
                ('skirting_height', models.CharField(default='0', max_length=250)),
                ('skirting_pattern', models.BooleanField(default=False)),
                ('skirting_color', models.CharField(default='white', max_length=250)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('skirting_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('tiling_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
