# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        #('demo', '0007_auto_20170830_2150'),
        #('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('pymba', '0004_pymbapartitionpage_pymbapartitionpagelayers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pymbawallpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pymbawallpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='pymbawallpagelayers',
            name='page',
        ),
        migrations.DeleteModel(
            name='PymbaWallPage',
        ),
        migrations.DeleteModel(
            name='PymbaWallPageLayers',
        ),
    ]
