# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymba', '0005_auto_20180302_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpage',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
