# Generated by Django 2.0.2 on 2018-08-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('pymba', '0006_auto_20180316_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PymbaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='color',
            field=models.CharField(blank=True, help_text='Accepts hex (#ffffff) or HTML color', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Sets the finishing general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='intro',
            field=models.CharField(blank=True, help_text='Finishing description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='pattern',
            field=models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?'),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='skirting_color',
            field=models.CharField(default='white', help_text='Accepts hex (#ffffff) or HTML color', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='skirting_height',
            field=models.CharField(default='0', help_text='Skirting height from in cm', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='skirting_image',
            field=models.ForeignKey(blank=True, help_text='Sets the skirting general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='skirting_pattern',
            field=models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?'),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='tiling_color',
            field=models.CharField(default='white', help_text='Accepts hex (#ffffff) or HTML color', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='tiling_height',
            field=models.CharField(default='0', help_text='Tiling height from floor in cm', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='tiling_image',
            field=models.ForeignKey(blank=True, help_text='Sets the tiling general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='tiling_pattern',
            field=models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?'),
        ),
        migrations.AlterField(
            model_name='pymbapage',
            name='double_face',
            field=models.BooleanField(default=False, help_text='Planes are visible on both sides?'),
        ),
        migrations.AlterField(
            model_name='pymbapage',
            name='dxf_file',
            field=models.ForeignKey(help_text='CAD file of your project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='pymbapage',
            name='equirectangular_image',
            field=models.ForeignKey(blank=True, help_text='Landscape surrounding your project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='pymbapage',
            name='fly_camera',
            field=models.BooleanField(default=False, help_text='Vertical movement of camera?'),
        ),
        migrations.AlterField(
            model_name='pymbapage',
            name='intro',
            field=models.CharField(blank=True, help_text='Project description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pymbapage',
            name='shadows',
            field=models.BooleanField(default=False, help_text='Want to cast shadows?'),
        ),
        migrations.AlterField(
            model_name='pymbapagematerialimage',
            name='color',
            field=models.CharField(default='white', help_text='Accepts hex (#ffffff) or HTML color', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbapagematerialimage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Sets general appearance of material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='pymbapagematerialimage',
            name='layer',
            field=models.CharField(default='0', help_text='Layer name in CAD file', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbapagematerialimage',
            name='pattern',
            field=models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?'),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpage',
            name='color',
            field=models.CharField(blank=True, help_text='Accepts hex (#ffffff) or HTML color', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Sets the partition general appearance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpage',
            name='intro',
            field=models.CharField(blank=True, help_text='Partition description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpage',
            name='pattern',
            field=models.BooleanField(default=False, help_text='Is it a 1x1 meter pattern?'),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpagelayers',
            name='material',
            field=models.CharField(default='brick', help_text='Material description', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpagelayers',
            name='thickness',
            field=models.CharField(default='0', help_text='In centimeters', max_length=250),
        ),
        migrations.AlterField(
            model_name='pymbapartitionpagelayers',
            name='weight',
            field=models.CharField(default='0', help_text='In kilos per cubic meter', max_length=250),
        ),
    ]
