# Generated by Django 2.0.9 on 2018-10-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymba', '0007_auto_20180815_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='pymbapagematerialimage',
            name='invisible',
            field=models.BooleanField(default=False, help_text='Hide layer?'),
        ),
        migrations.AlterField(
            model_name='pymbafinishingpage',
            name='skirting_height',
            field=models.CharField(default='0', help_text='Skirting height from floor in cm', max_length=250),
        ),
    ]
